/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockSwapRouterInterface extends Interface {
    getFunction(nameOrSignature: "amountOut" | "expectedTokenIn" | "expectedTokenOut" | "setAmountOut" | "swapExactInput"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'amountOut', values?: undefined): string;
encodeFunctionData(functionFragment: 'expectedTokenIn', values?: undefined): string;
encodeFunctionData(functionFragment: 'expectedTokenOut', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAmountOut', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapExactInput', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'amountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expectedTokenIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expectedTokenOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAmountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactInput', data: BytesLike): Result;
  }

  

  export interface MockSwapRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockSwapRouter;
    waitForDeployment(): Promise<this>;

    interface: MockSwapRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    amountOut: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    expectedTokenIn: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    expectedTokenOut: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAmountOut: TypedContractMethod<
      [configuredAmountOut: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swapExactInput: TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, minAmountOut: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'amountOut'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'expectedTokenIn'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'expectedTokenOut'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAmountOut'): TypedContractMethod<
      [configuredAmountOut: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapExactInput'): TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, minAmountOut: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }