/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockNoxveilEngineInterface extends Interface {
    getFunction(nameOrSignature: "commitEpoch" | "executeResidual" | "releaseEpoch" | "reserveForEpoch" | "vault"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'commitEpoch', values: [BytesLike, AddressLike, BytesLike, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'executeResidual', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'releaseEpoch', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'reserveForEpoch', values: [BytesLike, AddressLike, BytesLike, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'vault', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'commitEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeResidual', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveForEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vault', data: BytesLike): Result;
  }

  

  export interface MockNoxveilEngine extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockNoxveilEngine;
    waitForDeployment(): Promise<this>;

    interface: MockNoxveilEngineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    commitEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, wethCreditHandle: BytesLike, wethCreditProof: BytesLike, usdcCreditHandle: BytesLike, usdcCreditProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    executeResidual: TypedContractMethod<
      [direction: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    releaseEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    reserveForEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, directionHandle: BytesLike, directionProof: BytesLike, clipHandle: BytesLike, clipProof: BytesLike, ],
      [[string, string] & {wethReservedHandle: string, usdcReservedHandle: string }],
      'nonpayable'
    >
    

    
    vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'commitEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, wethCreditHandle: BytesLike, wethCreditProof: BytesLike, usdcCreditHandle: BytesLike, usdcCreditProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeResidual'): TypedContractMethod<
      [direction: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reserveForEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, directionHandle: BytesLike, directionProof: BytesLike, clipHandle: BytesLike, clipProof: BytesLike, ],
      [[string, string] & {wethReservedHandle: string, usdcReservedHandle: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }