/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockUniswapV3PoolInterface extends Interface {
    getFunction(nameOrSignature: "fee" | "liquidity" | "maxHistory" | "meanTick" | "observe" | "setLiquidity" | "setMaxHistory" | "setObservation" | "setSpotTick" | "slot0" | "spotTick" | "tickCumulativeDelta" | "token0" | "token1"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'fee', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidity', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxHistory', values?: undefined): string;
encodeFunctionData(functionFragment: 'meanTick', values?: undefined): string;
encodeFunctionData(functionFragment: 'observe', values: [BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'setLiquidity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMaxHistory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setObservation', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setSpotTick', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'slot0', values?: undefined): string;
encodeFunctionData(functionFragment: 'spotTick', values?: undefined): string;
encodeFunctionData(functionFragment: 'tickCumulativeDelta', values?: undefined): string;
encodeFunctionData(functionFragment: 'token0', values?: undefined): string;
encodeFunctionData(functionFragment: 'token1', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'fee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'meanTick', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'observe', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMaxHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setObservation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSpotTick', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slot0', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spotTick', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tickCumulativeDelta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token0', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token1', data: BytesLike): Result;
  }

  

  export interface MockUniswapV3Pool extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockUniswapV3Pool;
    waitForDeployment(): Promise<this>;

    interface: MockUniswapV3PoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    fee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    liquidity: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxHistory: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    meanTick: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    observe: TypedContractMethod<
      [secondsAgos: BigNumberish[], ],
      [[bigint[], bigint[]] & {tickCumulatives: bigint[], secondsPerLiquidity: bigint[] }],
      'view'
    >
    

    
    setLiquidity: TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMaxHistory: TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setObservation: TypedContractMethod<
      [history: BigNumberish, delta: BigNumberish, arg2: BigNumberish, configuredSpotTick: BigNumberish, configuredLiquidity: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setSpotTick: TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    slot0: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, boolean]],
      'view'
    >
    

    
    spotTick: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tickCumulativeDelta: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    token0: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token1: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'fee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'liquidity'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxHistory'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'meanTick'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'observe'): TypedContractMethod<
      [secondsAgos: BigNumberish[], ],
      [[bigint[], bigint[]] & {tickCumulatives: bigint[], secondsPerLiquidity: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'setLiquidity'): TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMaxHistory'): TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setObservation'): TypedContractMethod<
      [history: BigNumberish, delta: BigNumberish, arg2: BigNumberish, configuredSpotTick: BigNumberish, configuredLiquidity: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSpotTick'): TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slot0'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, boolean]],
      'view'
    >;
getFunction(nameOrSignature: 'spotTick'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tickCumulativeDelta'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'token0'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token1'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }