/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace NoxveilTypes {
      
    export type ActionCommitmentInputStruct = {chainId: BigNumberish, engine: AddressLike, vault: AddressLike, adapter: AddressLike, epochId: BytesLike, epochNonce: BigNumberish, deadline: BigNumberish, weth: AddressLike, usdc: AddressLike, uniswapRouter: AddressLike, uniswapPool: AddressLike, fee: BigNumberish, twapWindow: BigNumberish, twapPriceWad: BigNumberish, residualDirectionHandle: BytesLike, residualAmountHandle: BytesLike, aggregateMinOutHandle: BytesLike}

    export type ActionCommitmentInputStructOutput = [chainId: bigint, engine: string, vault: string, adapter: string, epochId: string, epochNonce: bigint, deadline: bigint, weth: string, usdc: string, uniswapRouter: string, uniswapPool: string, fee: bigint, twapWindow: bigint, twapPriceWad: bigint, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string] & {chainId: bigint, engine: string, vault: string, adapter: string, epochId: string, epochNonce: bigint, deadline: bigint, weth: string, usdc: string, uniswapRouter: string, uniswapPool: string, fee: bigint, twapWindow: bigint, twapPriceWad: bigint, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string }
  
    }

  export interface NoxveilMathHarnessInterface extends Interface {
    getFunction(nameOrSignature: "actionCommitment" | "finalDust" | "proRata" | "quoteWadToUsdc" | "quoteWadToUsdcUp" | "quoteWadToWeth" | "quoteWadToWethUp" | "residual" | "usdcToQuoteWad" | "validateFee" | "wethToQuoteWad"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'actionCommitment', values: [NoxveilTypes.ActionCommitmentInputStruct]): string;
encodeFunctionData(functionFragment: 'finalDust', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'proRata', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteWadToUsdc', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteWadToUsdcUp', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteWadToWeth', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteWadToWethUp', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'residual', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdcToQuoteWad', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validateFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'wethToQuoteWad', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'actionCommitment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalDust', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proRata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteWadToUsdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteWadToUsdcUp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteWadToWeth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteWadToWethUp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'residual', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToQuoteWad', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'wethToQuoteWad', data: BytesLike): Result;
  }

  

  export interface NoxveilMathHarness extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxveilMathHarness;
    waitForDeployment(): Promise<this>;

    interface: NoxveilMathHarnessInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    actionCommitment: TypedContractMethod<
      [input: NoxveilTypes.ActionCommitmentInputStruct, ],
      [string],
      'view'
    >
    

    
    finalDust: TypedContractMethod<
      [totalOutput: BigNumberish, allocatedBefore: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    proRata: TypedContractMethod<
      [totalOutput: BigNumberish, userInput: BigNumberish, sideInput: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteWadToUsdc: TypedContractMethod<
      [quoteWad: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteWadToUsdcUp: TypedContractMethod<
      [quoteWad: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteWadToWeth: TypedContractMethod<
      [quoteWad: BigNumberish, priceWad: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteWadToWethUp: TypedContractMethod<
      [quoteWad: BigNumberish, priceWad: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    residual: TypedContractMethod<
      [wethWei: BigNumberish, usdcAtoms: BigNumberish, priceWad: BigNumberish, ],
      [[bigint, bigint, bigint] & {direction: bigint, amountIn: bigint, matchedQuoteWad: bigint }],
      'view'
    >
    

    
    usdcToQuoteWad: TypedContractMethod<
      [usdcAtoms: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    validateFee: TypedContractMethod<
      [fee: BigNumberish, ],
      [void],
      'view'
    >
    

    
    wethToQuoteWad: TypedContractMethod<
      [wethWei: BigNumberish, priceWad: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'actionCommitment'): TypedContractMethod<
      [input: NoxveilTypes.ActionCommitmentInputStruct, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'finalDust'): TypedContractMethod<
      [totalOutput: BigNumberish, allocatedBefore: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proRata'): TypedContractMethod<
      [totalOutput: BigNumberish, userInput: BigNumberish, sideInput: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteWadToUsdc'): TypedContractMethod<
      [quoteWad: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteWadToUsdcUp'): TypedContractMethod<
      [quoteWad: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteWadToWeth'): TypedContractMethod<
      [quoteWad: BigNumberish, priceWad: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteWadToWethUp'): TypedContractMethod<
      [quoteWad: BigNumberish, priceWad: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'residual'): TypedContractMethod<
      [wethWei: BigNumberish, usdcAtoms: BigNumberish, priceWad: BigNumberish, ],
      [[bigint, bigint, bigint] & {direction: bigint, amountIn: bigint, matchedQuoteWad: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'usdcToQuoteWad'): TypedContractMethod<
      [usdcAtoms: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'validateFee'): TypedContractMethod<
      [fee: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'wethToQuoteWad'): TypedContractMethod<
      [wethWei: BigNumberish, priceWad: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }