/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBatchSwapRouter, IBatchSwapRouterInterface } from "../../interfaces/IBatchSwapRouter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "tokenIn",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "tokenOut",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "minAmountOut",
        "type": "uint256"
      }
    ],
    "name": "swapExactInput",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "amountOut",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IBatchSwapRouter__factory {
    static readonly abi = _abi;
    static createInterface(): IBatchSwapRouterInterface {
      return new Interface(_abi) as IBatchSwapRouterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBatchSwapRouter {
      return new Contract(address, _abi, runner) as unknown as IBatchSwapRouter;
    }
  }
  