/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INoxBatchEvaluator, INoxBatchEvaluatorInterface } from "../../interfaces/INoxBatchEvaluator.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "epoch",
        "type": "uint64"
      },
      {
        "internalType": "address[3]",
        "name": "users",
        "type": "address[3]"
      },
      {
        "internalType": "bytes32[3]",
        "name": "amountHandles",
        "type": "bytes32[3]"
      },
      {
        "internalType": "bytes[3]",
        "name": "amountProofs",
        "type": "bytes[3]"
      },
      {
        "internalType": "bytes32[3]",
        "name": "minOutHandles",
        "type": "bytes32[3]"
      },
      {
        "internalType": "bytes[3]",
        "name": "minOutProofs",
        "type": "bytes[3]"
      },
      {
        "internalType": "uint128[3]",
        "name": "escrowCaps",
        "type": "uint128[3]"
      }
    ],
    "name": "requestNetting",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "requestId",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class INoxBatchEvaluator__factory {
    static readonly abi = _abi;
    static createInterface(): INoxBatchEvaluatorInterface {
      return new Interface(_abi) as INoxBatchEvaluatorInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): INoxBatchEvaluator {
      return new Contract(address, _abi, runner) as unknown as INoxBatchEvaluator;
    }
  }
  