/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace ISwapRouter02Minimal {
      
    export type ExactInputSingleParamsStruct = {tokenIn: AddressLike, tokenOut: AddressLike, fee: BigNumberish, recipient: AddressLike, amountIn: BigNumberish, amountOutMinimum: BigNumberish, sqrtPriceLimitX96: BigNumberish}

    export type ExactInputSingleParamsStructOutput = [tokenIn: string, tokenOut: string, fee: bigint, recipient: string, amountIn: bigint, amountOutMinimum: bigint, sqrtPriceLimitX96: bigint] & {tokenIn: string, tokenOut: string, fee: bigint, recipient: string, amountIn: bigint, amountOutMinimum: bigint, sqrtPriceLimitX96: bigint }
  
    }

  export interface MockSwapRouter02Interface extends Interface {
    getFunction(nameOrSignature: "amountOut" | "callCount" | "exactInputSingle" | "lastCall" | "setAmountOut"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'amountOut', values?: undefined): string;
encodeFunctionData(functionFragment: 'callCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'exactInputSingle', values: [ISwapRouter02Minimal.ExactInputSingleParamsStruct]): string;
encodeFunctionData(functionFragment: 'lastCall', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAmountOut', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'amountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'callCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exactInputSingle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAmountOut', data: BytesLike): Result;
  }

  

  export interface MockSwapRouter02 extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockSwapRouter02;
    waitForDeployment(): Promise<this>;

    interface: MockSwapRouter02Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    amountOut: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    callCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    exactInputSingle: TypedContractMethod<
      [params: ISwapRouter02Minimal.ExactInputSingleParamsStruct, ],
      [bigint],
      'payable'
    >
    

    
    lastCall: TypedContractMethod<
      [],
      [[string, string, bigint, string, bigint, bigint, bigint] & {tokenIn: string, tokenOut: string, fee: bigint, recipient: string, amountIn: bigint, amountOutMinimum: bigint, sqrtPriceLimitX96: bigint }],
      'view'
    >
    

    
    setAmountOut: TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'amountOut'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'callCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'exactInputSingle'): TypedContractMethod<
      [params: ISwapRouter02Minimal.ExactInputSingleParamsStruct, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'lastCall'): TypedContractMethod<
      [],
      [[string, string, bigint, string, bigint, bigint, bigint] & {tokenIn: string, tokenOut: string, fee: bigint, recipient: string, amountIn: bigint, amountOutMinimum: bigint, sqrtPriceLimitX96: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'setAmountOut'): TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }