/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockUniswapV3Factory, MockUniswapV3FactoryInterface } from "../../test/MockUniswapV3Factory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "tokenA",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "tokenB",
        "type": "address"
      },
      {
        "internalType": "uint24",
        "name": "fee",
        "type": "uint24"
      }
    ],
    "name": "getPool",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "tokenA",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "tokenB",
        "type": "address"
      },
      {
        "internalType": "uint24",
        "name": "fee",
        "type": "uint24"
      },
      {
        "internalType": "address",
        "name": "pool",
        "type": "address"
      }
    ],
    "name": "setPool",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061025a8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c80631698ee8214610038578063e9321d1514610067575b5f5ffd5b61004b610046366004610193565b61007c565b6040516001600160a01b03909116815260200160405180910390f35b61007a6100753660046101d3565b6100ab565b005b5f5f5f61008a8686866100ef565b815260208101919091526040015f20546001600160a01b0316949350505050565b805f5f6100b98787876100ef565b81526020019081526020015f205f6101000a8154816001600160a01b0302191690836001600160a01b0316021790555050505050565b5f5f5f846001600160a01b0316866001600160a01b031610610112578486610115565b85855b604080516001600160a01b03808516602083015283169181019190915262ffffff87166060820152919350915060800160405160208183030381529060405280519060200120925050509392505050565b80356001600160a01b038116811461017c575f5ffd5b919050565b803562ffffff8116811461017c575f5ffd5b5f5f5f606084860312156101a5575f5ffd5b6101ae84610166565b92506101bc60208501610166565b91506101ca60408501610181565b90509250925092565b5f5f5f5f608085870312156101e6575f5ffd5b6101ef85610166565b93506101fd60208601610166565b925061020b60408601610181565b915061021960608601610166565b90509295919450925056fea264697066735822122021707b08a1bb74a431af7bd77de7d445b34a5a035e30bab7c7e6d45f61f81df264736f6c63430008230033";

  
      type MockUniswapV3FactoryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockUniswapV3FactoryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockUniswapV3Factory__factory extends ContractFactory {
    
      constructor(...args: MockUniswapV3FactoryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockUniswapV3Factory & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockUniswapV3Factory__factory {
      return super.connect(runner) as MockUniswapV3Factory__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockUniswapV3FactoryInterface {
      return new Interface(_abi) as MockUniswapV3FactoryInterface;
    }
    
    override attach(address: string | Addressable): MockUniswapV3Factory {
      return super.attach(address) as MockUniswapV3Factory;
    }
  static connect(address: string, runner?: ContractRunner | null): MockUniswapV3Factory {
      return new Contract(address, _abi, runner) as unknown as MockUniswapV3Factory;
    }
  }

  
  