/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockNoxveilAdapter, MockNoxveilAdapterInterface } from "../../test/MockNoxveilAdapter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "configuredVault",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "consultTwap",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "priceWad",
        "type": "uint256"
      },
      {
        "internalType": "int24",
        "name": "arithmeticMeanTick",
        "type": "int24"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amountOutMinimum",
        "type": "uint256"
      }
    ],
    "name": "executeResidual",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "amountOut",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "fee",
    "outputs": [
      {
        "internalType": "uint24",
        "name": "",
        "type": "uint24"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "pool",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "router",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "twapWindow",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "usdc",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "vault",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "weth",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a060405234801561000f575f5ffd5b5060405161039238038061039283398101604081905261002e91610144565b6001600160a01b038116608081905260408051633fc8cef360e01b81529051633fc8cef3916004808201926020929091908290030181865afa158015610076573d5f5f3e3d5ffd5b505050506040513d601f19601f8201168201806040525081019061009a9190610144565b5f5f6101000a8154816001600160a01b0302191690836001600160a01b03160217905550806001600160a01b0316633e413bee6040518163ffffffff1660e01b8152600401602060405180830381865afa1580156100fa573d5f5f3e3d5ffd5b505050506040513d601f19601f8201168201806040525081019061011e9190610144565b600180546001600160a01b0319166001600160a01b039290921691909117905550610171565b5f60208284031215610154575f5ffd5b81516001600160a01b038116811461016a575f5ffd5b9392505050565b6080516102096101895f395f61017a01526102095ff3fe608060405234801561000f575f5ffd5b5060043610610090575f3560e01c80638107e133116100635780638107e1331461010b578063ddca3f4314610129578063e91f1c1d14610146578063f887ea4014610162578063fbfa77cf14610175575f5ffd5b806316f0115b146100945780633e413bee146100c45780633fc8cef3146100d75780634533b1c6146100e9575b5f5ffd5b6002546100a7906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b6001546100a7906001600160a01b031681565b5f546100a7906001600160a01b031681565b6100fd6100f736600461019c565b92915050565b6040519081526020016100bb565b61011461070881565b60405163ffffffff90911681526020016100bb565b6101326101f481565b60405162ffffff90911681526020016100bb565b6040805168878678326eac90000081525f6020820152016100bb565b6003546100a7906001600160a01b031681565b6100a77f000000000000000000000000000000000000000000000000000000000000000081565b5f5f5f606084860312156101ae575f5ffd5b833560ff811681146101be575f5ffd5b9560208501359550604090940135939250505056fea2646970667358221220954c3b4e4d4ece8ce298be29a835309b442d33c0da488b734758d089379a1bb764736f6c63430008230033";

  
      type MockNoxveilAdapterConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockNoxveilAdapterConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockNoxveilAdapter__factory extends ContractFactory {
    
      constructor(...args: MockNoxveilAdapterConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(configuredVault: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(configuredVault, overrides || {});
    };
    override deploy(configuredVault: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(configuredVault, overrides || {}) as Promise<MockNoxveilAdapter & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockNoxveilAdapter__factory {
      return super.connect(runner) as MockNoxveilAdapter__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockNoxveilAdapterInterface {
      return new Interface(_abi) as MockNoxveilAdapterInterface;
    }
    
    override attach(address: string | Addressable): MockNoxveilAdapter {
      return super.attach(address) as MockNoxveilAdapter;
    }
  static connect(address: string, runner?: ContractRunner | null): MockNoxveilAdapter {
      return new Contract(address, _abi, runner) as unknown as MockNoxveilAdapter;
    }
  }

  
  