/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'INoxBatchRouterCallback', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INoxBatchRouterCallback__factory>
getContractFactory(name: 'NoxBatchEvaluator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxBatchEvaluator__factory>
getContractFactory(name: 'NoxBatchRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxBatchRouter__factory>
getContractFactory(name: 'NoxBatchRouterV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxBatchRouterV2__factory>
getContractFactory(name: 'IUniswapV3SwapRouter02', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV3SwapRouter02__factory>
getContractFactory(name: 'UniswapV3BatchSwapAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UniswapV3BatchSwapAdapter__factory>
getContractFactory(name: 'IBatchSwapRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBatchSwapRouter__factory>
getContractFactory(name: 'IERC20Minimal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20Minimal__factory>
getContractFactory(name: 'INoxBatchEvaluator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INoxBatchEvaluator__factory>
getContractFactory(name: 'INoxBatchRouterCallback', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INoxBatchRouterCallback__factory>
getContractFactory(name: 'MockBatchEvaluator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockBatchEvaluator__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockERC20Decimals', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20Decimals__factory>
getContractFactory(name: 'MockNoxveilEngine', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockNoxveilEngine__factory>
getContractFactory(name: 'IMockMintableToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMockMintableToken__factory>
getContractFactory(name: 'MockNoxveilAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockNoxveilAdapter__factory>
getContractFactory(name: 'IMintableToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMintableToken__factory>
getContractFactory(name: 'MockSwapRouter02', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockSwapRouter02__factory>
getContractFactory(name: 'MockSwapRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockSwapRouter__factory>
getContractFactory(name: 'MockUniswapV3Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUniswapV3Factory__factory>
getContractFactory(name: 'MockUniswapV3Pool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUniswapV3Pool__factory>
getContractFactory(name: 'NoxveilEpochStateHarness', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxveilEpochStateHarness__factory>
getContractFactory(name: 'NoxveilMathHarness', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxveilMathHarness__factory>
getContractFactory(name: 'NoxveilEpochState', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxveilEpochState__factory>
getContractFactory(name: 'NoxveilUniswapV3Adapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxveilUniswapV3Adapter__factory>
getContractFactory(name: 'NoxveilStrategyEngine', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxveilStrategyEngine__factory>
getContractFactory(name: 'INoxveilEngineBinding', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INoxveilEngineBinding__factory>
getContractFactory(name: 'NoxveilVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxveilVault__factory>
getContractFactory(name: 'NoxveilMath', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxveilMath__factory>
getContractFactory(name: 'NoxveilTickMath', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoxveilTickMath__factory>
getContractFactory(name: 'IERC20MetadataMinimal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20MetadataMinimal__factory>
getContractFactory(name: 'INoxveilAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INoxveilAdapter__factory>
getContractFactory(name: 'INoxveilVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INoxveilVault__factory>
getContractFactory(name: 'IUniswapV3FactoryMinimal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV3FactoryMinimal__factory>
getContractFactory(name: 'ISwapRouter02Minimal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISwapRouter02Minimal__factory>
getContractFactory(name: 'IUniswapV3PoolMinimal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV3PoolMinimal__factory>

  getContractAt(name: 'INoxBatchRouterCallback', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INoxBatchRouterCallback>
getContractAt(name: 'NoxBatchEvaluator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxBatchEvaluator>
getContractAt(name: 'NoxBatchRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxBatchRouter>
getContractAt(name: 'NoxBatchRouterV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxBatchRouterV2>
getContractAt(name: 'IUniswapV3SwapRouter02', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV3SwapRouter02>
getContractAt(name: 'UniswapV3BatchSwapAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UniswapV3BatchSwapAdapter>
getContractAt(name: 'IBatchSwapRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBatchSwapRouter>
getContractAt(name: 'IERC20Minimal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20Minimal>
getContractAt(name: 'INoxBatchEvaluator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INoxBatchEvaluator>
getContractAt(name: 'INoxBatchRouterCallback', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INoxBatchRouterCallback>
getContractAt(name: 'MockBatchEvaluator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockBatchEvaluator>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockERC20Decimals', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20Decimals>
getContractAt(name: 'MockNoxveilEngine', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockNoxveilEngine>
getContractAt(name: 'IMockMintableToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMockMintableToken>
getContractAt(name: 'MockNoxveilAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockNoxveilAdapter>
getContractAt(name: 'IMintableToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMintableToken>
getContractAt(name: 'MockSwapRouter02', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockSwapRouter02>
getContractAt(name: 'MockSwapRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockSwapRouter>
getContractAt(name: 'MockUniswapV3Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUniswapV3Factory>
getContractAt(name: 'MockUniswapV3Pool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUniswapV3Pool>
getContractAt(name: 'NoxveilEpochStateHarness', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxveilEpochStateHarness>
getContractAt(name: 'NoxveilMathHarness', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxveilMathHarness>
getContractAt(name: 'NoxveilEpochState', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxveilEpochState>
getContractAt(name: 'NoxveilUniswapV3Adapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxveilUniswapV3Adapter>
getContractAt(name: 'NoxveilStrategyEngine', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxveilStrategyEngine>
getContractAt(name: 'INoxveilEngineBinding', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INoxveilEngineBinding>
getContractAt(name: 'NoxveilVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxveilVault>
getContractAt(name: 'NoxveilMath', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxveilMath>
getContractAt(name: 'NoxveilTickMath', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoxveilTickMath>
getContractAt(name: 'IERC20MetadataMinimal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20MetadataMinimal>
getContractAt(name: 'INoxveilAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INoxveilAdapter>
getContractAt(name: 'INoxveilVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INoxveilVault>
getContractAt(name: 'IUniswapV3FactoryMinimal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV3FactoryMinimal>
getContractAt(name: 'ISwapRouter02Minimal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISwapRouter02Minimal>
getContractAt(name: 'IUniswapV3PoolMinimal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV3PoolMinimal>

  deployContract(name: 'INoxBatchRouterCallback', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxBatchRouterCallback>
deployContract(name: 'NoxBatchEvaluator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxBatchEvaluator>
deployContract(name: 'NoxBatchRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxBatchRouter>
deployContract(name: 'NoxBatchRouterV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxBatchRouterV2>
deployContract(name: 'IUniswapV3SwapRouter02', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV3SwapRouter02>
deployContract(name: 'UniswapV3BatchSwapAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV3BatchSwapAdapter>
deployContract(name: 'IBatchSwapRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBatchSwapRouter>
deployContract(name: 'IERC20Minimal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Minimal>
deployContract(name: 'INoxBatchEvaluator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxBatchEvaluator>
deployContract(name: 'INoxBatchRouterCallback', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxBatchRouterCallback>
deployContract(name: 'MockBatchEvaluator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockBatchEvaluator>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockERC20Decimals', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20Decimals>
deployContract(name: 'MockNoxveilEngine', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockNoxveilEngine>
deployContract(name: 'IMockMintableToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMockMintableToken>
deployContract(name: 'MockNoxveilAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockNoxveilAdapter>
deployContract(name: 'IMintableToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMintableToken>
deployContract(name: 'MockSwapRouter02', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockSwapRouter02>
deployContract(name: 'MockSwapRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockSwapRouter>
deployContract(name: 'MockUniswapV3Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV3Factory>
deployContract(name: 'MockUniswapV3Pool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV3Pool>
deployContract(name: 'NoxveilEpochStateHarness', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilEpochStateHarness>
deployContract(name: 'NoxveilMathHarness', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilMathHarness>
deployContract(name: 'NoxveilEpochState', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilEpochState>
deployContract(name: 'NoxveilUniswapV3Adapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilUniswapV3Adapter>
deployContract(name: 'NoxveilStrategyEngine', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilStrategyEngine>
deployContract(name: 'INoxveilEngineBinding', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxveilEngineBinding>
deployContract(name: 'NoxveilVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilVault>
deployContract(name: 'NoxveilMath', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilMath>
deployContract(name: 'NoxveilTickMath', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilTickMath>
deployContract(name: 'IERC20MetadataMinimal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20MetadataMinimal>
deployContract(name: 'INoxveilAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxveilAdapter>
deployContract(name: 'INoxveilVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxveilVault>
deployContract(name: 'IUniswapV3FactoryMinimal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV3FactoryMinimal>
deployContract(name: 'ISwapRouter02Minimal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISwapRouter02Minimal>
deployContract(name: 'IUniswapV3PoolMinimal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV3PoolMinimal>

  deployContract(name: 'INoxBatchRouterCallback', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxBatchRouterCallback>
deployContract(name: 'NoxBatchEvaluator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxBatchEvaluator>
deployContract(name: 'NoxBatchRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxBatchRouter>
deployContract(name: 'NoxBatchRouterV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxBatchRouterV2>
deployContract(name: 'IUniswapV3SwapRouter02', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV3SwapRouter02>
deployContract(name: 'UniswapV3BatchSwapAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV3BatchSwapAdapter>
deployContract(name: 'IBatchSwapRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBatchSwapRouter>
deployContract(name: 'IERC20Minimal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Minimal>
deployContract(name: 'INoxBatchEvaluator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxBatchEvaluator>
deployContract(name: 'INoxBatchRouterCallback', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxBatchRouterCallback>
deployContract(name: 'MockBatchEvaluator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockBatchEvaluator>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockERC20Decimals', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20Decimals>
deployContract(name: 'MockNoxveilEngine', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockNoxveilEngine>
deployContract(name: 'IMockMintableToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMockMintableToken>
deployContract(name: 'MockNoxveilAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockNoxveilAdapter>
deployContract(name: 'IMintableToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMintableToken>
deployContract(name: 'MockSwapRouter02', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockSwapRouter02>
deployContract(name: 'MockSwapRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockSwapRouter>
deployContract(name: 'MockUniswapV3Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV3Factory>
deployContract(name: 'MockUniswapV3Pool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUniswapV3Pool>
deployContract(name: 'NoxveilEpochStateHarness', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilEpochStateHarness>
deployContract(name: 'NoxveilMathHarness', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilMathHarness>
deployContract(name: 'NoxveilEpochState', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilEpochState>
deployContract(name: 'NoxveilUniswapV3Adapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilUniswapV3Adapter>
deployContract(name: 'NoxveilStrategyEngine', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilStrategyEngine>
deployContract(name: 'INoxveilEngineBinding', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxveilEngineBinding>
deployContract(name: 'NoxveilVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilVault>
deployContract(name: 'NoxveilMath', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilMath>
deployContract(name: 'NoxveilTickMath', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoxveilTickMath>
deployContract(name: 'IERC20MetadataMinimal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20MetadataMinimal>
deployContract(name: 'INoxveilAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxveilAdapter>
deployContract(name: 'INoxveilVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INoxveilVault>
deployContract(name: 'IUniswapV3FactoryMinimal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV3FactoryMinimal>
deployContract(name: 'ISwapRouter02Minimal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISwapRouter02Minimal>
deployContract(name: 'IUniswapV3PoolMinimal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV3PoolMinimal>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  