/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace NoxBatchRouterV2 {
      
    export type EpochStruct = {deadline: BigNumberish, status: BigNumberish, intentCount: BigNumberish, evaluationAttempts: BigNumberish, epoch: BigNumberish, requestedAt: BigNumberish, requestId: BytesLike, totalInput: BigNumberish, totalOutput: BigNumberish}

    export type EpochStructOutput = [deadline: bigint, status: bigint, intentCount: bigint, evaluationAttempts: bigint, epoch: bigint, requestedAt: bigint, requestId: string, totalInput: bigint, totalOutput: bigint] & {deadline: bigint, status: bigint, intentCount: bigint, evaluationAttempts: bigint, epoch: bigint, requestedAt: bigint, requestId: string, totalInput: bigint, totalOutput: bigint }
  
    }

  export interface NoxBatchRouterV2Interface extends Interface {
    getFunction(nameOrSignature: "BATCH_SIZE" | "MAX_EVALUATION_ATTEMPTS" | "MAX_TIMEOUT" | "activeEpochId" | "amountHandle" | "cancelEpoch" | "epochIdUsed" | "evaluationTimeout" | "evaluator" | "finalizeNetting" | "getEpoch" | "handleUsed" | "openEpoch" | "requestIdUsed" | "requestNetting" | "router" | "settle" | "submitIntent(bytes32,bytes32,bytes32,uint128)" | "submitIntent(bytes32,bytes32,bytes,bytes32,bytes,uint128)" | "tokenIn" | "tokenOut" | "userAt"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EpochCancelled" | "EpochOpened" | "EpochSettled" | "IntentSubmitted" | "NettingFinalized" | "NettingRequestFailed" | "NettingRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'BATCH_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_EVALUATION_ATTEMPTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_TIMEOUT', values?: undefined): string;
encodeFunctionData(functionFragment: 'activeEpochId', values?: undefined): string;
encodeFunctionData(functionFragment: 'amountHandle', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelEpoch', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'epochIdUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'evaluationTimeout', values?: undefined): string;
encodeFunctionData(functionFragment: 'evaluator', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalizeNetting', values: [BytesLike, BytesLike, BigNumberish, BigNumberish, [BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish]]): string;
encodeFunctionData(functionFragment: 'getEpoch', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'handleUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'openEpoch', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'requestIdUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'requestNetting', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'router', values?: undefined): string;
encodeFunctionData(functionFragment: 'settle', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitIntent(bytes32,bytes32,bytes32,uint128)', values: [BytesLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitIntent(bytes32,bytes32,bytes,bytes32,bytes,uint128)', values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenIn', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenOut', values?: undefined): string;
encodeFunctionData(functionFragment: 'userAt', values: [BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BATCH_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_EVALUATION_ATTEMPTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_TIMEOUT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeEpochId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'amountHandle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochIdUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'evaluationTimeout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'evaluator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeNetting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestIdUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestNetting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitIntent(bytes32,bytes32,bytes32,uint128)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitIntent(bytes32,bytes32,bytes,bytes32,bytes,uint128)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userAt', data: BytesLike): Result;
  }

  
    export namespace EpochCancelledEvent {
      export type InputTuple = [epochId: BytesLike, caller: AddressLike];
      export type OutputTuple = [epochId: string, caller: string];
      export interface OutputObject {epochId: string, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochOpenedEvent {
      export type InputTuple = [epochId: BytesLike, deadline: BigNumberish];
      export type OutputTuple = [epochId: string, deadline: bigint];
      export interface OutputObject {epochId: string, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochSettledEvent {
      export type InputTuple = [epochId: BytesLike, amountIn: BigNumberish, minAmountOut: BigNumberish];
      export type OutputTuple = [epochId: string, amountIn: bigint, minAmountOut: bigint];
      export interface OutputObject {epochId: string, amountIn: bigint, minAmountOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentSubmittedEvent {
      export type InputTuple = [epochId: BytesLike, user: AddressLike, amountHandle: BytesLike, minOutHandle: BytesLike, escrowCap: BigNumberish];
      export type OutputTuple = [epochId: string, user: string, amountHandle: string, minOutHandle: string, escrowCap: bigint];
      export interface OutputObject {epochId: string, user: string, amountHandle: string, minOutHandle: string, escrowCap: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NettingFinalizedEvent {
      export type InputTuple = [epochId: BytesLike, totalInput: BigNumberish, totalOutput: BigNumberish];
      export type OutputTuple = [epochId: string, totalInput: bigint, totalOutput: bigint];
      export interface OutputObject {epochId: string, totalInput: bigint, totalOutput: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NettingRequestFailedEvent {
      export type InputTuple = [epochId: BytesLike, epoch: BigNumberish, attempt: BigNumberish];
      export type OutputTuple = [epochId: string, epoch: bigint, attempt: bigint];
      export interface OutputObject {epochId: string, epoch: bigint, attempt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NettingRequestedEvent {
      export type InputTuple = [epochId: BytesLike, requestId: BytesLike, epoch: BigNumberish, attempt: BigNumberish];
      export type OutputTuple = [epochId: string, requestId: string, epoch: bigint, attempt: bigint];
      export interface OutputObject {epochId: string, requestId: string, epoch: bigint, attempt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxBatchRouterV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxBatchRouterV2;
    waitForDeployment(): Promise<this>;

    interface: NoxBatchRouterV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BATCH_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_EVALUATION_ATTEMPTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_TIMEOUT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activeEpochId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    amountHandle: TypedContractMethod<
      [epochId: BytesLike, index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    cancelEpoch: TypedContractMethod<
      [epochId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    epochIdUsed: TypedContractMethod<
      [epochId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    evaluationTimeout: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    evaluator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    finalizeNetting: TypedContractMethod<
      [epochId: BytesLike, requestId: BytesLike, epoch: BigNumberish, totalInput: BigNumberish, debits: [BigNumberish, BigNumberish, BigNumberish], outputs: [BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >
    

    
    getEpoch: TypedContractMethod<
      [epochId: BytesLike, ],
      [NoxBatchRouterV2.EpochStructOutput],
      'view'
    >
    

    
    handleUsed: TypedContractMethod<
      [handle: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    openEpoch: TypedContractMethod<
      [epochId: BytesLike, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    requestIdUsed: TypedContractMethod<
      [requestId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    requestNetting: TypedContractMethod<
      [epochId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    settle: TypedContractMethod<
      [epochId: BytesLike, minAmountOut: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "submitIntent(bytes32,bytes32,bytes32,uint128)": TypedContractMethod<
      [epochId: BytesLike, encryptedAmountHandle: BytesLike, encryptedMinOutHandle: BytesLike, escrowCap: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "submitIntent(bytes32,bytes32,bytes,bytes32,bytes,uint128)": TypedContractMethod<
      [epochId: BytesLike, encryptedAmountHandle: BytesLike, encryptedAmountProof: BytesLike, encryptedMinOutHandle: BytesLike, encryptedMinOutProof: BytesLike, escrowCap: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tokenIn: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenOut: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    userAt: TypedContractMethod<
      [epochId: BytesLike, index: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BATCH_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_EVALUATION_ATTEMPTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_TIMEOUT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activeEpochId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'amountHandle'): TypedContractMethod<
      [epochId: BytesLike, index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelEpoch'): TypedContractMethod<
      [epochId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'epochIdUsed'): TypedContractMethod<
      [epochId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'evaluationTimeout'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'evaluator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeNetting'): TypedContractMethod<
      [epochId: BytesLike, requestId: BytesLike, epoch: BigNumberish, totalInput: BigNumberish, debits: [BigNumberish, BigNumberish, BigNumberish], outputs: [BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEpoch'): TypedContractMethod<
      [epochId: BytesLike, ],
      [NoxBatchRouterV2.EpochStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'handleUsed'): TypedContractMethod<
      [handle: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'openEpoch'): TypedContractMethod<
      [epochId: BytesLike, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestIdUsed'): TypedContractMethod<
      [requestId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'requestNetting'): TypedContractMethod<
      [epochId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'settle'): TypedContractMethod<
      [epochId: BytesLike, minAmountOut: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitIntent(bytes32,bytes32,bytes32,uint128)'): TypedContractMethod<
      [epochId: BytesLike, encryptedAmountHandle: BytesLike, encryptedMinOutHandle: BytesLike, escrowCap: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitIntent(bytes32,bytes32,bytes,bytes32,bytes,uint128)'): TypedContractMethod<
      [epochId: BytesLike, encryptedAmountHandle: BytesLike, encryptedAmountProof: BytesLike, encryptedMinOutHandle: BytesLike, encryptedMinOutProof: BytesLike, escrowCap: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenIn'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenOut'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'userAt'): TypedContractMethod<
      [epochId: BytesLike, index: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'EpochCancelled'): TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
getEvent(key: 'EpochOpened'): TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
getEvent(key: 'EpochSettled'): TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
getEvent(key: 'IntentSubmitted'): TypedContractEvent<IntentSubmittedEvent.InputTuple, IntentSubmittedEvent.OutputTuple, IntentSubmittedEvent.OutputObject>;
getEvent(key: 'NettingFinalized'): TypedContractEvent<NettingFinalizedEvent.InputTuple, NettingFinalizedEvent.OutputTuple, NettingFinalizedEvent.OutputObject>;
getEvent(key: 'NettingRequestFailed'): TypedContractEvent<NettingRequestFailedEvent.InputTuple, NettingRequestFailedEvent.OutputTuple, NettingRequestFailedEvent.OutputObject>;
getEvent(key: 'NettingRequested'): TypedContractEvent<NettingRequestedEvent.InputTuple, NettingRequestedEvent.OutputTuple, NettingRequestedEvent.OutputObject>;

    filters: {
      
      'EpochCancelled(bytes32,address)': TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
      EpochCancelled: TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
    

      'EpochOpened(bytes32,uint64)': TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
      EpochOpened: TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
    

      'EpochSettled(bytes32,uint128,uint128)': TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
      EpochSettled: TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
    

      'IntentSubmitted(bytes32,address,bytes32,bytes32,uint128)': TypedContractEvent<IntentSubmittedEvent.InputTuple, IntentSubmittedEvent.OutputTuple, IntentSubmittedEvent.OutputObject>;
      IntentSubmitted: TypedContractEvent<IntentSubmittedEvent.InputTuple, IntentSubmittedEvent.OutputTuple, IntentSubmittedEvent.OutputObject>;
    

      'NettingFinalized(bytes32,uint128,uint128)': TypedContractEvent<NettingFinalizedEvent.InputTuple, NettingFinalizedEvent.OutputTuple, NettingFinalizedEvent.OutputObject>;
      NettingFinalized: TypedContractEvent<NettingFinalizedEvent.InputTuple, NettingFinalizedEvent.OutputTuple, NettingFinalizedEvent.OutputObject>;
    

      'NettingRequestFailed(bytes32,uint64,uint8)': TypedContractEvent<NettingRequestFailedEvent.InputTuple, NettingRequestFailedEvent.OutputTuple, NettingRequestFailedEvent.OutputObject>;
      NettingRequestFailed: TypedContractEvent<NettingRequestFailedEvent.InputTuple, NettingRequestFailedEvent.OutputTuple, NettingRequestFailedEvent.OutputObject>;
    

      'NettingRequested(bytes32,bytes32,uint64,uint8)': TypedContractEvent<NettingRequestedEvent.InputTuple, NettingRequestedEvent.OutputTuple, NettingRequestedEvent.OutputObject>;
      NettingRequested: TypedContractEvent<NettingRequestedEvent.InputTuple, NettingRequestedEvent.OutputTuple, NettingRequestedEvent.OutputObject>;
    
    };
  }