/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface INoxveilVaultInterface extends Interface {
    getFunction(nameOrSignature: "adapter" | "availableHandle" | "commitEpoch" | "engine" | "executeResidual" | "releaseEpoch" | "reserveForEpoch" | "usdc" | "weth"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'adapter', values?: undefined): string;
encodeFunctionData(functionFragment: 'availableHandle', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'commitEpoch', values: [BytesLike, AddressLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'engine', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeResidual', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'releaseEpoch', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'reserveForEpoch', values: [BytesLike, AddressLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'weth', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'adapter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'availableHandle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'engine', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeResidual', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveForEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weth', data: BytesLike): Result;
  }

  

  export interface INoxveilVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): INoxveilVault;
    waitForDeployment(): Promise<this>;

    interface: INoxveilVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    adapter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    availableHandle: TypedContractMethod<
      [owner: AddressLike, token: AddressLike, ],
      [string],
      'view'
    >
    

    
    commitEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, wethCreditHandle: BytesLike, usdcCreditHandle: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    engine: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeResidual: TypedContractMethod<
      [direction: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    releaseEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    reserveForEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, directionHandle: BytesLike, selectedClipHandle: BytesLike, ],
      [[string, string] & {wethReservedHandle: string, usdcReservedHandle: string }],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    weth: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'adapter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'availableHandle'): TypedContractMethod<
      [owner: AddressLike, token: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'commitEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, wethCreditHandle: BytesLike, usdcCreditHandle: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'engine'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeResidual'): TypedContractMethod<
      [direction: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reserveForEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, directionHandle: BytesLike, selectedClipHandle: BytesLike, ],
      [[string, string] & {wethReservedHandle: string, usdcReservedHandle: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'weth'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }