/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMintableToken, IMintableTokenInterface } from "../../../test/MockSwapRouter02.sol/IMintableToken.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMintableToken__factory {
    static readonly abi = _abi;
    static createInterface(): IMintableTokenInterface {
      return new Interface(_abi) as IMintableTokenInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMintableToken {
      return new Contract(address, _abi, runner) as unknown as IMintableToken;
    }
  }
  