/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMockMintableToken } from './IMockMintableToken.js';
export type { MockNoxveilAdapter } from './MockNoxveilAdapter.js';