/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockNoxveilAdapterInterface extends Interface {
    getFunction(nameOrSignature: "callCount" | "configuredAmountOut" | "consultTwap" | "executeResidual" | "fee" | "pool" | "router" | "setAmountOut" | "setShouldRevert" | "shouldRevert" | "twapWindow" | "usdc" | "vault" | "weth"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'callCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'configuredAmountOut', values?: undefined): string;
encodeFunctionData(functionFragment: 'consultTwap', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeResidual', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fee', values?: undefined): string;
encodeFunctionData(functionFragment: 'pool', values?: undefined): string;
encodeFunctionData(functionFragment: 'router', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAmountOut', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setShouldRevert', values: [boolean]): string;
encodeFunctionData(functionFragment: 'shouldRevert', values?: undefined): string;
encodeFunctionData(functionFragment: 'twapWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'vault', values?: undefined): string;
encodeFunctionData(functionFragment: 'weth', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'callCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'configuredAmountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'consultTwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeResidual', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAmountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setShouldRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shouldRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'twapWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weth', data: BytesLike): Result;
  }

  

  export interface MockNoxveilAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockNoxveilAdapter;
    waitForDeployment(): Promise<this>;

    interface: MockNoxveilAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    callCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    configuredAmountOut: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    consultTwap: TypedContractMethod<
      [],
      [[bigint, bigint] & {priceWad: bigint, arithmeticMeanTick: bigint }],
      'view'
    >
    

    
    executeResidual: TypedContractMethod<
      [direction: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    fee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAmountOut: TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setShouldRevert: TypedContractMethod<
      [value: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    shouldRevert: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    twapWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    weth: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'callCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'configuredAmountOut'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'consultTwap'): TypedContractMethod<
      [],
      [[bigint, bigint] & {priceWad: bigint, arithmeticMeanTick: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'executeResidual'): TypedContractMethod<
      [direction: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAmountOut'): TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setShouldRevert'): TypedContractMethod<
      [value: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shouldRevert'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'twapWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'weth'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }