/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMockMintableToken, IMockMintableTokenInterface } from "../../../test/MockNoxveilAdapter.sol/IMockMintableToken.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMockMintableToken__factory {
    static readonly abi = _abi;
    static createInterface(): IMockMintableTokenInterface {
      return new Interface(_abi) as IMockMintableTokenInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMockMintableToken {
      return new Contract(address, _abi, runner) as unknown as IMockMintableToken;
    }
  }
  