/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace NoxveilVault {
      
    export type FullWithdrawalStruct = {owner: AddressLike, token: AddressLike, destination: AddressLike, nonce: BigNumberish, deadline: BigNumberish, balanceHandle: BytesLike, consumed: boolean}

    export type FullWithdrawalStructOutput = [owner: string, token: string, destination: string, nonce: bigint, deadline: bigint, balanceHandle: string, consumed: boolean] & {owner: string, token: string, destination: string, nonce: bigint, deadline: bigint, balanceHandle: string, consumed: boolean }
  
    }

  export interface NoxveilVaultInterface extends Interface {
    getFunction(nameOrSignature: "activeReservationCount" | "adapter" | "availableHandle" | "bootstrapAdmin" | "bootstrapClosed" | "closeBootstrap" | "commitEpoch" | "deposit" | "engine" | "executeResidual" | "finalizeFullWithdrawal" | "getFullWithdrawal" | "pendingWithdrawal" | "releaseEpoch" | "requestFullWithdrawal" | "reservationCreated" | "reservationProcessed" | "reserveForEpoch" | "reservedHandle" | "setAdapter" | "setEngine" | "usdc" | "weth" | "withdrawalNonceUsed"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdapterBound" | "BootstrapPermanentlyClosed" | "Deposited" | "EngineBound" | "EpochReservationCommitted" | "EpochReservationReleased" | "EpochReserved" | "FullWithdrawalFinalized" | "FullWithdrawalRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'activeReservationCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'adapter', values?: undefined): string;
encodeFunctionData(functionFragment: 'availableHandle', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'bootstrapAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'bootstrapClosed', values?: undefined): string;
encodeFunctionData(functionFragment: 'closeBootstrap', values?: undefined): string;
encodeFunctionData(functionFragment: 'commitEpoch', values: [BytesLike, AddressLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'deposit', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'engine', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeResidual', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeFullWithdrawal', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getFullWithdrawal', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'pendingWithdrawal', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'releaseEpoch', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'requestFullWithdrawal', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reservationCreated', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'reservationProcessed', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'reserveForEpoch', values: [BytesLike, AddressLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'reservedHandle', values: [BytesLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setAdapter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setEngine', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'weth', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawalNonceUsed', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'activeReservationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adapter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'availableHandle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bootstrapAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bootstrapClosed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeBootstrap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'engine', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeResidual', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeFullWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFullWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestFullWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reservationCreated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reservationProcessed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveForEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reservedHandle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAdapter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEngine', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawalNonceUsed', data: BytesLike): Result;
  }

  
    export namespace AdapterBoundEvent {
      export type InputTuple = [adapter: AddressLike];
      export type OutputTuple = [adapter: string];
      export interface OutputObject {adapter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BootstrapPermanentlyClosedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [owner: AddressLike, token: AddressLike];
      export type OutputTuple = [owner: string, token: string];
      export interface OutputObject {owner: string, token: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EngineBoundEvent {
      export type InputTuple = [engine: AddressLike];
      export type OutputTuple = [engine: string];
      export interface OutputObject {engine: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochReservationCommittedEvent {
      export type InputTuple = [epochId: BytesLike, owner: AddressLike];
      export type OutputTuple = [epochId: string, owner: string];
      export interface OutputObject {epochId: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochReservationReleasedEvent {
      export type InputTuple = [epochId: BytesLike, owner: AddressLike];
      export type OutputTuple = [epochId: string, owner: string];
      export interface OutputObject {epochId: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochReservedEvent {
      export type InputTuple = [epochId: BytesLike, owner: AddressLike];
      export type OutputTuple = [epochId: string, owner: string];
      export interface OutputObject {epochId: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FullWithdrawalFinalizedEvent {
      export type InputTuple = [commitment: BytesLike, owner: AddressLike, token: AddressLike, destination: AddressLike];
      export type OutputTuple = [commitment: string, owner: string, token: string, destination: string];
      export interface OutputObject {commitment: string, owner: string, token: string, destination: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FullWithdrawalRequestedEvent {
      export type InputTuple = [commitment: BytesLike, owner: AddressLike, token: AddressLike, destination: AddressLike, nonce: BigNumberish, deadline: BigNumberish, balanceHandle: BytesLike];
      export type OutputTuple = [commitment: string, owner: string, token: string, destination: string, nonce: bigint, deadline: bigint, balanceHandle: string];
      export interface OutputObject {commitment: string, owner: string, token: string, destination: string, nonce: bigint, deadline: bigint, balanceHandle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxveilVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxveilVault;
    waitForDeployment(): Promise<this>;

    interface: NoxveilVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activeReservationCount: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    adapter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    availableHandle: TypedContractMethod<
      [owner: AddressLike, token: AddressLike, ],
      [string],
      'view'
    >
    

    
    bootstrapAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    bootstrapClosed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    closeBootstrap: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    commitEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, wethCreditHandle: BytesLike, usdcCreditHandle: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    engine: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeResidual: TypedContractMethod<
      [direction: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    finalizeFullWithdrawal: TypedContractMethod<
      [commitment: BytesLike, decryptionProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getFullWithdrawal: TypedContractMethod<
      [commitment: BytesLike, ],
      [NoxveilVault.FullWithdrawalStructOutput],
      'view'
    >
    

    
    pendingWithdrawal: TypedContractMethod<
      [owner: AddressLike, token: AddressLike, ],
      [string],
      'view'
    >
    

    
    releaseEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestFullWithdrawal: TypedContractMethod<
      [token: AddressLike, destination: AddressLike, nonce: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    reservationCreated: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    reservationProcessed: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    reserveForEpoch: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, directionHandle: BytesLike, selectedClipHandle: BytesLike, ],
      [[string, string] & {wethReservedHandle: string, usdcReservedHandle: string }],
      'nonpayable'
    >
    

    
    reservedHandle: TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, token: AddressLike, ],
      [string],
      'view'
    >
    

    
    setAdapter: TypedContractMethod<
      [candidate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setEngine: TypedContractMethod<
      [candidate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    weth: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawalNonceUsed: TypedContractMethod<
      [owner: AddressLike, nonce: BigNumberish, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activeReservationCount'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'adapter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'availableHandle'): TypedContractMethod<
      [owner: AddressLike, token: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'bootstrapAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'bootstrapClosed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'closeBootstrap'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commitEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, wethCreditHandle: BytesLike, usdcCreditHandle: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'engine'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeResidual'): TypedContractMethod<
      [direction: BigNumberish, amountIn: BigNumberish, amountOutMinimum: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeFullWithdrawal'): TypedContractMethod<
      [commitment: BytesLike, decryptionProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getFullWithdrawal'): TypedContractMethod<
      [commitment: BytesLike, ],
      [NoxveilVault.FullWithdrawalStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'pendingWithdrawal'): TypedContractMethod<
      [owner: AddressLike, token: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestFullWithdrawal'): TypedContractMethod<
      [token: AddressLike, destination: AddressLike, nonce: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reservationCreated'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'reservationProcessed'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'reserveForEpoch'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, directionHandle: BytesLike, selectedClipHandle: BytesLike, ],
      [[string, string] & {wethReservedHandle: string, usdcReservedHandle: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reservedHandle'): TypedContractMethod<
      [epochId: BytesLike, owner: AddressLike, token: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAdapter'): TypedContractMethod<
      [candidate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEngine'): TypedContractMethod<
      [candidate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'weth'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawalNonceUsed'): TypedContractMethod<
      [owner: AddressLike, nonce: BigNumberish, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'AdapterBound'): TypedContractEvent<AdapterBoundEvent.InputTuple, AdapterBoundEvent.OutputTuple, AdapterBoundEvent.OutputObject>;
getEvent(key: 'BootstrapPermanentlyClosed'): TypedContractEvent<BootstrapPermanentlyClosedEvent.InputTuple, BootstrapPermanentlyClosedEvent.OutputTuple, BootstrapPermanentlyClosedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'EngineBound'): TypedContractEvent<EngineBoundEvent.InputTuple, EngineBoundEvent.OutputTuple, EngineBoundEvent.OutputObject>;
getEvent(key: 'EpochReservationCommitted'): TypedContractEvent<EpochReservationCommittedEvent.InputTuple, EpochReservationCommittedEvent.OutputTuple, EpochReservationCommittedEvent.OutputObject>;
getEvent(key: 'EpochReservationReleased'): TypedContractEvent<EpochReservationReleasedEvent.InputTuple, EpochReservationReleasedEvent.OutputTuple, EpochReservationReleasedEvent.OutputObject>;
getEvent(key: 'EpochReserved'): TypedContractEvent<EpochReservedEvent.InputTuple, EpochReservedEvent.OutputTuple, EpochReservedEvent.OutputObject>;
getEvent(key: 'FullWithdrawalFinalized'): TypedContractEvent<FullWithdrawalFinalizedEvent.InputTuple, FullWithdrawalFinalizedEvent.OutputTuple, FullWithdrawalFinalizedEvent.OutputObject>;
getEvent(key: 'FullWithdrawalRequested'): TypedContractEvent<FullWithdrawalRequestedEvent.InputTuple, FullWithdrawalRequestedEvent.OutputTuple, FullWithdrawalRequestedEvent.OutputObject>;

    filters: {
      
      'AdapterBound(address)': TypedContractEvent<AdapterBoundEvent.InputTuple, AdapterBoundEvent.OutputTuple, AdapterBoundEvent.OutputObject>;
      AdapterBound: TypedContractEvent<AdapterBoundEvent.InputTuple, AdapterBoundEvent.OutputTuple, AdapterBoundEvent.OutputObject>;
    

      'BootstrapPermanentlyClosed()': TypedContractEvent<BootstrapPermanentlyClosedEvent.InputTuple, BootstrapPermanentlyClosedEvent.OutputTuple, BootstrapPermanentlyClosedEvent.OutputObject>;
      BootstrapPermanentlyClosed: TypedContractEvent<BootstrapPermanentlyClosedEvent.InputTuple, BootstrapPermanentlyClosedEvent.OutputTuple, BootstrapPermanentlyClosedEvent.OutputObject>;
    

      'Deposited(address,address)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'EngineBound(address)': TypedContractEvent<EngineBoundEvent.InputTuple, EngineBoundEvent.OutputTuple, EngineBoundEvent.OutputObject>;
      EngineBound: TypedContractEvent<EngineBoundEvent.InputTuple, EngineBoundEvent.OutputTuple, EngineBoundEvent.OutputObject>;
    

      'EpochReservationCommitted(bytes32,address)': TypedContractEvent<EpochReservationCommittedEvent.InputTuple, EpochReservationCommittedEvent.OutputTuple, EpochReservationCommittedEvent.OutputObject>;
      EpochReservationCommitted: TypedContractEvent<EpochReservationCommittedEvent.InputTuple, EpochReservationCommittedEvent.OutputTuple, EpochReservationCommittedEvent.OutputObject>;
    

      'EpochReservationReleased(bytes32,address)': TypedContractEvent<EpochReservationReleasedEvent.InputTuple, EpochReservationReleasedEvent.OutputTuple, EpochReservationReleasedEvent.OutputObject>;
      EpochReservationReleased: TypedContractEvent<EpochReservationReleasedEvent.InputTuple, EpochReservationReleasedEvent.OutputTuple, EpochReservationReleasedEvent.OutputObject>;
    

      'EpochReserved(bytes32,address)': TypedContractEvent<EpochReservedEvent.InputTuple, EpochReservedEvent.OutputTuple, EpochReservedEvent.OutputObject>;
      EpochReserved: TypedContractEvent<EpochReservedEvent.InputTuple, EpochReservedEvent.OutputTuple, EpochReservedEvent.OutputObject>;
    

      'FullWithdrawalFinalized(bytes32,address,address,address)': TypedContractEvent<FullWithdrawalFinalizedEvent.InputTuple, FullWithdrawalFinalizedEvent.OutputTuple, FullWithdrawalFinalizedEvent.OutputObject>;
      FullWithdrawalFinalized: TypedContractEvent<FullWithdrawalFinalizedEvent.InputTuple, FullWithdrawalFinalizedEvent.OutputTuple, FullWithdrawalFinalizedEvent.OutputObject>;
    

      'FullWithdrawalRequested(bytes32,address,address,address,uint64,uint64,bytes32)': TypedContractEvent<FullWithdrawalRequestedEvent.InputTuple, FullWithdrawalRequestedEvent.OutputTuple, FullWithdrawalRequestedEvent.OutputObject>;
      FullWithdrawalRequested: TypedContractEvent<FullWithdrawalRequestedEvent.InputTuple, FullWithdrawalRequestedEvent.OutputTuple, FullWithdrawalRequestedEvent.OutputObject>;
    
    };
  }