/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INoxBatchRouterCallback, INoxBatchRouterCallbackInterface } from "../../../test/MockBatchEvaluator.sol/INoxBatchRouterCallback.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "requestId",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "epoch",
        "type": "uint64"
      },
      {
        "internalType": "uint128",
        "name": "totalInput",
        "type": "uint128"
      },
      {
        "internalType": "uint128[3]",
        "name": "debits",
        "type": "uint128[3]"
      },
      {
        "internalType": "uint128[3]",
        "name": "outputs",
        "type": "uint128[3]"
      }
    ],
    "name": "finalizeNetting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class INoxBatchRouterCallback__factory {
    static readonly abi = _abi;
    static createInterface(): INoxBatchRouterCallbackInterface {
      return new Interface(_abi) as INoxBatchRouterCallbackInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): INoxBatchRouterCallback {
      return new Contract(address, _abi, runner) as unknown as INoxBatchRouterCallback;
    }
  }
  