/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INoxveilEngineBinding, INoxveilEngineBindingInterface } from "../../../v3/NoxveilVault.sol/INoxveilEngineBinding.js";

  const _abi = [
  {
    "inputs": [],
    "name": "vault",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class INoxveilEngineBinding__factory {
    static readonly abi = _abi;
    static createInterface(): INoxveilEngineBindingInterface {
      return new Interface(_abi) as INoxveilEngineBindingInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): INoxveilEngineBinding {
      return new Contract(address, _abi, runner) as unknown as INoxveilEngineBinding;
    }
  }
  