/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INoxBatchRouterCallback } from './INoxBatchRouterCallback.js';
export type { MockBatchEvaluator } from './MockBatchEvaluator.js';