/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface INoxBatchRouterCallbackInterface extends Interface {
    getFunction(nameOrSignature: "finalizeNetting"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'finalizeNetting', values: [BytesLike, BytesLike, BigNumberish, BigNumberish, [BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish]]): string;

    decodeFunctionResult(functionFragment: 'finalizeNetting', data: BytesLike): Result;
  }

  

  export interface INoxBatchRouterCallback extends BaseContract {
    
    connect(runner?: ContractRunner | null): INoxBatchRouterCallback;
    waitForDeployment(): Promise<this>;

    interface: INoxBatchRouterCallbackInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    finalizeNetting: TypedContractMethod<
      [epochId: BytesLike, requestId: BytesLike, epoch: BigNumberish, totalInput: BigNumberish, debits: [BigNumberish, BigNumberish, BigNumberish], outputs: [BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'finalizeNetting'): TypedContractMethod<
      [epochId: BytesLike, requestId: BytesLike, epoch: BigNumberish, totalInput: BigNumberish, debits: [BigNumberish, BigNumberish, BigNumberish], outputs: [BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }