/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockBatchEvaluatorInterface extends Interface {
    getFunction(nameOrSignature: "finalize" | "nextRequestId" | "requestNetting" | "reverting" | "setNextRequestId" | "setReverting"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'finalize', values: [AddressLike, BytesLike, BytesLike, BigNumberish, BigNumberish, [BigNumberish, BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish]]): string;
encodeFunctionData(functionFragment: 'nextRequestId', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestNetting', values: [BytesLike, BigNumberish, [AddressLike, AddressLike, AddressLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BigNumberish, BigNumberish, BigNumberish]]): string;
encodeFunctionData(functionFragment: 'reverting', values?: undefined): string;
encodeFunctionData(functionFragment: 'setNextRequestId', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setReverting', values: [boolean]): string;

    decodeFunctionResult(functionFragment: 'finalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextRequestId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestNetting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reverting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNextRequestId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReverting', data: BytesLike): Result;
  }

  

  export interface MockBatchEvaluator extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockBatchEvaluator;
    waitForDeployment(): Promise<this>;

    interface: MockBatchEvaluatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    finalize: TypedContractMethod<
      [batchRouter: AddressLike, epochId: BytesLike, requestId: BytesLike, epoch: BigNumberish, totalInput: BigNumberish, debits: [BigNumberish, BigNumberish, BigNumberish], outputs: [BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >
    

    
    nextRequestId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    requestNetting: TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, arg2: [AddressLike, AddressLike, AddressLike], arg3: [BytesLike, BytesLike, BytesLike], arg4: [BytesLike, BytesLike, BytesLike], arg5: [BytesLike, BytesLike, BytesLike], arg6: [BytesLike, BytesLike, BytesLike], arg7: [BigNumberish, BigNumberish, BigNumberish], ],
      [string],
      'view'
    >
    

    
    reverting: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setNextRequestId: TypedContractMethod<
      [requestId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setReverting: TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'finalize'): TypedContractMethod<
      [batchRouter: AddressLike, epochId: BytesLike, requestId: BytesLike, epoch: BigNumberish, totalInput: BigNumberish, debits: [BigNumberish, BigNumberish, BigNumberish], outputs: [BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextRequestId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requestNetting'): TypedContractMethod<
      [arg0: BytesLike, arg1: BigNumberish, arg2: [AddressLike, AddressLike, AddressLike], arg3: [BytesLike, BytesLike, BytesLike], arg4: [BytesLike, BytesLike, BytesLike], arg5: [BytesLike, BytesLike, BytesLike], arg6: [BytesLike, BytesLike, BytesLike], arg7: [BigNumberish, BigNumberish, BigNumberish], ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reverting'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setNextRequestId'): TypedContractMethod<
      [requestId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReverting'): TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }