/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface INoxBatchEvaluatorInterface extends Interface {
    getFunction(nameOrSignature: "requestNetting"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'requestNetting', values: [BytesLike, BigNumberish, [AddressLike, AddressLike, AddressLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BigNumberish, BigNumberish, BigNumberish]]): string;

    decodeFunctionResult(functionFragment: 'requestNetting', data: BytesLike): Result;
  }

  

  export interface INoxBatchEvaluator extends BaseContract {
    
    connect(runner?: ContractRunner | null): INoxBatchEvaluator;
    waitForDeployment(): Promise<this>;

    interface: INoxBatchEvaluatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    requestNetting: TypedContractMethod<
      [epochId: BytesLike, epoch: BigNumberish, users: [AddressLike, AddressLike, AddressLike], amountHandles: [BytesLike, BytesLike, BytesLike], amountProofs: [BytesLike, BytesLike, BytesLike], minOutHandles: [BytesLike, BytesLike, BytesLike], minOutProofs: [BytesLike, BytesLike, BytesLike], escrowCaps: [BigNumberish, BigNumberish, BigNumberish], ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'requestNetting'): TypedContractMethod<
      [epochId: BytesLike, epoch: BigNumberish, users: [AddressLike, AddressLike, AddressLike], amountHandles: [BytesLike, BytesLike, BytesLike], amountProofs: [BytesLike, BytesLike, BytesLike], minOutHandles: [BytesLike, BytesLike, BytesLike], minOutProofs: [BytesLike, BytesLike, BytesLike], escrowCaps: [BigNumberish, BigNumberish, BigNumberish], ],
      [string],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }