/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace NoxveilStrategyEngine {
      
    export type ExternalStrategyInputStruct = {direction: BytesLike, directionProof: BytesLike, budget: BytesLike, budgetProof: BytesLike, clip: BytesLike, clipProof: BytesLike, limitPriceWad: BytesLike, limitPriceProof: BytesLike, slippageBps: BytesLike, slippageProof: BytesLike}

    export type ExternalStrategyInputStructOutput = [direction: string, directionProof: string, budget: string, budgetProof: string, clip: string, clipProof: string, limitPriceWad: string, limitPriceProof: string, slippageBps: string, slippageProof: string] & {direction: string, directionProof: string, budget: string, budgetProof: string, clip: string, clipProof: string, limitPriceWad: string, limitPriceProof: string, slippageBps: string, slippageProof: string }
  

    export type EpochPrivateHandleSetStruct = {totalWeth: BytesLike, totalUsdc: BytesLike, totalRequestedQuote: BytesLike, matchedQuote: BytesLike}

    export type EpochPrivateHandleSetStructOutput = [totalWeth: string, totalUsdc: string, totalRequestedQuote: string, matchedQuote: string] & {totalWeth: string, totalUsdc: string, totalRequestedQuote: string, matchedQuote: string }
  

    export type EpochStrategyHandleSetStruct = {selectedWeth: BytesLike, selectedUsdc: BytesLike, reservationId: BytesLike}

    export type EpochStrategyHandleSetStructOutput = [selectedWeth: string, selectedUsdc: string, reservationId: string] & {selectedWeth: string, selectedUsdc: string, reservationId: string }
  

    export type StrategyPublicStruct = {owner: AddressLike, pairId: BytesLike, creationEpoch: BigNumberish, clientNonce: BigNumberish, slot: BigNumberish, cancelled: boolean}

    export type StrategyPublicStructOutput = [owner: string, pairId: string, creationEpoch: bigint, clientNonce: bigint, slot: bigint, cancelled: boolean] & {owner: string, pairId: string, creationEpoch: bigint, clientNonce: bigint, slot: bigint, cancelled: boolean }
  

    export type StrategyHandleSetStruct = {direction: BytesLike, remaining: BytesLike, clip: BytesLike, limitPriceWad: BytesLike, slippageBps: BytesLike}

    export type StrategyHandleSetStructOutput = [direction: string, remaining: string, clip: string, limitPriceWad: string, slippageBps: string] & {direction: string, remaining: string, clip: string, limitPriceWad: string, slippageBps: string }
  
    }

export declare namespace NoxveilEpochState {
      
    export type EpochPublicStruct = {openedAt: BigNumberish, lockedAt: BigNumberish, deadline: BigNumberish, participantCount: BigNumberish, epochNonce: BigNumberish, status: BigNumberish, twapPriceWad: BigNumberish, actionCommitment: BytesLike, residualDirectionHandle: BytesLike, residualAmountHandle: BytesLike, aggregateMinOutHandle: BytesLike, residualDirection: BigNumberish, residualAmount: BigNumberish, amountOutMinimum: BigNumberish, amountOut: BigNumberish}

    export type EpochPublicStructOutput = [openedAt: bigint, lockedAt: bigint, deadline: bigint, participantCount: bigint, epochNonce: bigint, status: bigint, twapPriceWad: bigint, actionCommitment: string, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string, residualDirection: bigint, residualAmount: bigint, amountOutMinimum: bigint, amountOut: bigint] & {openedAt: bigint, lockedAt: bigint, deadline: bigint, participantCount: bigint, epochNonce: bigint, status: bigint, twapPriceWad: bigint, actionCommitment: string, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string, residualDirection: bigint, residualAmount: bigint, amountOutMinimum: bigint, amountOut: bigint }
  
    }

  export interface NoxveilStrategyEngineInterface extends Interface {
    getFunction(nameOrSignature: "MAX_ACTIVE_STRATEGIES" | "activeStrategyAt" | "activeStrategyCount" | "adapter" | "auditor" | "auditorAdmin" | "cancelExpiredEpoch" | "cancelStrategy" | "clientNonceUsed" | "createStrategy" | "currentEpoch" | "epochDuration" | "epochIdUsed" | "epochNumberUsed" | "epochPrivateHandles" | "epochStrategyHandles" | "epochStrategyIncluded" | "finalizeAggregate" | "getEpoch" | "getStrategyPublic" | "handleUsed" | "increaseBudget" | "lockCurrentEpoch" | "pairId" | "setAuditor" | "settle" | "strategyHandles" | "strategyIdUsed" | "vault"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuditorUpdated" | "EpochCancelled" | "EpochLocked" | "EpochOpened" | "EpochReady" | "EpochSettled" | "StrategyBudgetIncreased" | "StrategyCancelled" | "StrategyCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_ACTIVE_STRATEGIES', values?: undefined): string;
encodeFunctionData(functionFragment: 'activeStrategyAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'activeStrategyCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'adapter', values?: undefined): string;
encodeFunctionData(functionFragment: 'auditor', values?: undefined): string;
encodeFunctionData(functionFragment: 'auditorAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelExpiredEpoch', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'cancelStrategy', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'clientNonceUsed', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createStrategy', values: [NoxveilStrategyEngine.ExternalStrategyInputStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'currentEpoch', values?: undefined): string;
encodeFunctionData(functionFragment: 'epochDuration', values?: undefined): string;
encodeFunctionData(functionFragment: 'epochIdUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'epochNumberUsed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'epochPrivateHandles', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'epochStrategyHandles', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'epochStrategyIncluded', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'finalizeAggregate', values: [BytesLike, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getEpoch', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getStrategyPublic', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'handleUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'increaseBudget', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'lockCurrentEpoch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pairId', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAuditor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'settle', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'strategyHandles', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'strategyIdUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'vault', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_ACTIVE_STRATEGIES', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeStrategyAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeStrategyCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adapter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auditor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auditorAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelExpiredEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clientNonceUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochIdUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochNumberUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochPrivateHandles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochStrategyHandles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochStrategyIncluded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeAggregate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStrategyPublic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increaseBudget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockCurrentEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pairId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuditor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'strategyHandles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'strategyIdUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vault', data: BytesLike): Result;
  }

  
    export namespace AuditorUpdatedEvent {
      export type InputTuple = [previousAuditor: AddressLike, newAuditor: AddressLike];
      export type OutputTuple = [previousAuditor: string, newAuditor: string];
      export interface OutputObject {previousAuditor: string, newAuditor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochCancelledEvent {
      export type InputTuple = [epochId: BytesLike];
      export type OutputTuple = [epochId: string];
      export interface OutputObject {epochId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochLockedEvent {
      export type InputTuple = [epochId: BytesLike, epochNonce: BigNumberish, twapPriceWad: BigNumberish, actionCommitment: BytesLike, residualDirectionHandle: BytesLike, residualAmountHandle: BytesLike, aggregateMinOutHandle: BytesLike];
      export type OutputTuple = [epochId: string, epochNonce: bigint, twapPriceWad: bigint, actionCommitment: string, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string];
      export interface OutputObject {epochId: string, epochNonce: bigint, twapPriceWad: bigint, actionCommitment: string, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochOpenedEvent {
      export type InputTuple = [epochId: BytesLike, epochNonce: BigNumberish, deadline: BigNumberish, participantCount: BigNumberish];
      export type OutputTuple = [epochId: string, epochNonce: bigint, deadline: bigint, participantCount: bigint];
      export interface OutputObject {epochId: string, epochNonce: bigint, deadline: bigint, participantCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochReadyEvent {
      export type InputTuple = [epochId: BytesLike, residualAmount: BigNumberish, amountOutMinimum: BigNumberish];
      export type OutputTuple = [epochId: string, residualAmount: bigint, amountOutMinimum: bigint];
      export interface OutputObject {epochId: string, residualAmount: bigint, amountOutMinimum: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochSettledEvent {
      export type InputTuple = [epochId: BytesLike, residualAmount: BigNumberish, amountOut: BigNumberish];
      export type OutputTuple = [epochId: string, residualAmount: bigint, amountOut: bigint];
      export interface OutputObject {epochId: string, residualAmount: bigint, amountOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyBudgetIncreasedEvent {
      export type InputTuple = [strategyId: BytesLike, owner: AddressLike];
      export type OutputTuple = [strategyId: string, owner: string];
      export interface OutputObject {strategyId: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyCancelledEvent {
      export type InputTuple = [strategyId: BytesLike, owner: AddressLike];
      export type OutputTuple = [strategyId: string, owner: string];
      export interface OutputObject {strategyId: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyCreatedEvent {
      export type InputTuple = [strategyId: BytesLike, owner: AddressLike, pairId: BytesLike, creationEpoch: BigNumberish, clientNonce: BigNumberish, slot: BigNumberish];
      export type OutputTuple = [strategyId: string, owner: string, pairId: string, creationEpoch: bigint, clientNonce: bigint, slot: bigint];
      export interface OutputObject {strategyId: string, owner: string, pairId: string, creationEpoch: bigint, clientNonce: bigint, slot: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxveilStrategyEngine extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxveilStrategyEngine;
    waitForDeployment(): Promise<this>;

    interface: NoxveilStrategyEngineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_ACTIVE_STRATEGIES: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activeStrategyAt: TypedContractMethod<
      [slot: BigNumberish, ],
      [string],
      'view'
    >
    

    
    activeStrategyCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    adapter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    auditor: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    auditorAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelExpiredEpoch: TypedContractMethod<
      [epochId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    cancelStrategy: TypedContractMethod<
      [strategyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    clientNonceUsed: TypedContractMethod<
      [owner: AddressLike, nonce: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    createStrategy: TypedContractMethod<
      [input: NoxveilStrategyEngine.ExternalStrategyInputStruct, clientNonce: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    currentEpoch: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    epochDuration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    epochIdUsed: TypedContractMethod<
      [epochId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    epochNumberUsed: TypedContractMethod<
      [epochNumber: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    epochPrivateHandles: TypedContractMethod<
      [epochId: BytesLike, ],
      [NoxveilStrategyEngine.EpochPrivateHandleSetStructOutput],
      'view'
    >
    

    
    epochStrategyHandles: TypedContractMethod<
      [epochId: BytesLike, strategyId: BytesLike, ],
      [NoxveilStrategyEngine.EpochStrategyHandleSetStructOutput],
      'view'
    >
    

    
    epochStrategyIncluded: TypedContractMethod<
      [epochId: BytesLike, strategyId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    finalizeAggregate: TypedContractMethod<
      [epochId: BytesLike, directionProof: BytesLike, amountProof: BytesLike, minimumProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getEpoch: TypedContractMethod<
      [epochId: BytesLike, ],
      [NoxveilEpochState.EpochPublicStructOutput],
      'view'
    >
    

    
    getStrategyPublic: TypedContractMethod<
      [strategyId: BytesLike, ],
      [NoxveilStrategyEngine.StrategyPublicStructOutput],
      'view'
    >
    

    
    handleUsed: TypedContractMethod<
      [handle: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    increaseBudget: TypedContractMethod<
      [strategyId: BytesLike, amountHandle: BytesLike, amountProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    lockCurrentEpoch: TypedContractMethod<
      [deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    pairId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAuditor: TypedContractMethod<
      [nextAuditor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    settle: TypedContractMethod<
      [epochId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    strategyHandles: TypedContractMethod<
      [strategyId: BytesLike, ],
      [NoxveilStrategyEngine.StrategyHandleSetStructOutput],
      'view'
    >
    

    
    strategyIdUsed: TypedContractMethod<
      [strategyId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_ACTIVE_STRATEGIES'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activeStrategyAt'): TypedContractMethod<
      [slot: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'activeStrategyCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'adapter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'auditor'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'auditorAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelExpiredEpoch'): TypedContractMethod<
      [epochId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelStrategy'): TypedContractMethod<
      [strategyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'clientNonceUsed'): TypedContractMethod<
      [owner: AddressLike, nonce: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createStrategy'): TypedContractMethod<
      [input: NoxveilStrategyEngine.ExternalStrategyInputStruct, clientNonce: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentEpoch'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'epochDuration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'epochIdUsed'): TypedContractMethod<
      [epochId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'epochNumberUsed'): TypedContractMethod<
      [epochNumber: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'epochPrivateHandles'): TypedContractMethod<
      [epochId: BytesLike, ],
      [NoxveilStrategyEngine.EpochPrivateHandleSetStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'epochStrategyHandles'): TypedContractMethod<
      [epochId: BytesLike, strategyId: BytesLike, ],
      [NoxveilStrategyEngine.EpochStrategyHandleSetStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'epochStrategyIncluded'): TypedContractMethod<
      [epochId: BytesLike, strategyId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeAggregate'): TypedContractMethod<
      [epochId: BytesLike, directionProof: BytesLike, amountProof: BytesLike, minimumProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEpoch'): TypedContractMethod<
      [epochId: BytesLike, ],
      [NoxveilEpochState.EpochPublicStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getStrategyPublic'): TypedContractMethod<
      [strategyId: BytesLike, ],
      [NoxveilStrategyEngine.StrategyPublicStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'handleUsed'): TypedContractMethod<
      [handle: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'increaseBudget'): TypedContractMethod<
      [strategyId: BytesLike, amountHandle: BytesLike, amountProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lockCurrentEpoch'): TypedContractMethod<
      [deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pairId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAuditor'): TypedContractMethod<
      [nextAuditor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settle'): TypedContractMethod<
      [epochId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'strategyHandles'): TypedContractMethod<
      [strategyId: BytesLike, ],
      [NoxveilStrategyEngine.StrategyHandleSetStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'strategyIdUsed'): TypedContractMethod<
      [strategyId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AuditorUpdated'): TypedContractEvent<AuditorUpdatedEvent.InputTuple, AuditorUpdatedEvent.OutputTuple, AuditorUpdatedEvent.OutputObject>;
getEvent(key: 'EpochCancelled'): TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
getEvent(key: 'EpochLocked'): TypedContractEvent<EpochLockedEvent.InputTuple, EpochLockedEvent.OutputTuple, EpochLockedEvent.OutputObject>;
getEvent(key: 'EpochOpened'): TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
getEvent(key: 'EpochReady'): TypedContractEvent<EpochReadyEvent.InputTuple, EpochReadyEvent.OutputTuple, EpochReadyEvent.OutputObject>;
getEvent(key: 'EpochSettled'): TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
getEvent(key: 'StrategyBudgetIncreased'): TypedContractEvent<StrategyBudgetIncreasedEvent.InputTuple, StrategyBudgetIncreasedEvent.OutputTuple, StrategyBudgetIncreasedEvent.OutputObject>;
getEvent(key: 'StrategyCancelled'): TypedContractEvent<StrategyCancelledEvent.InputTuple, StrategyCancelledEvent.OutputTuple, StrategyCancelledEvent.OutputObject>;
getEvent(key: 'StrategyCreated'): TypedContractEvent<StrategyCreatedEvent.InputTuple, StrategyCreatedEvent.OutputTuple, StrategyCreatedEvent.OutputObject>;

    filters: {
      
      'AuditorUpdated(address,address)': TypedContractEvent<AuditorUpdatedEvent.InputTuple, AuditorUpdatedEvent.OutputTuple, AuditorUpdatedEvent.OutputObject>;
      AuditorUpdated: TypedContractEvent<AuditorUpdatedEvent.InputTuple, AuditorUpdatedEvent.OutputTuple, AuditorUpdatedEvent.OutputObject>;
    

      'EpochCancelled(bytes32)': TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
      EpochCancelled: TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
    

      'EpochLocked(bytes32,uint32,uint256,bytes32,bytes32,bytes32,bytes32)': TypedContractEvent<EpochLockedEvent.InputTuple, EpochLockedEvent.OutputTuple, EpochLockedEvent.OutputObject>;
      EpochLocked: TypedContractEvent<EpochLockedEvent.InputTuple, EpochLockedEvent.OutputTuple, EpochLockedEvent.OutputObject>;
    

      'EpochOpened(bytes32,uint32,uint64,uint32)': TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
      EpochOpened: TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
    

      'EpochReady(bytes32,uint256,uint256)': TypedContractEvent<EpochReadyEvent.InputTuple, EpochReadyEvent.OutputTuple, EpochReadyEvent.OutputObject>;
      EpochReady: TypedContractEvent<EpochReadyEvent.InputTuple, EpochReadyEvent.OutputTuple, EpochReadyEvent.OutputObject>;
    

      'EpochSettled(bytes32,uint256,uint256)': TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
      EpochSettled: TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
    

      'StrategyBudgetIncreased(bytes32,address)': TypedContractEvent<StrategyBudgetIncreasedEvent.InputTuple, StrategyBudgetIncreasedEvent.OutputTuple, StrategyBudgetIncreasedEvent.OutputObject>;
      StrategyBudgetIncreased: TypedContractEvent<StrategyBudgetIncreasedEvent.InputTuple, StrategyBudgetIncreasedEvent.OutputTuple, StrategyBudgetIncreasedEvent.OutputObject>;
    

      'StrategyCancelled(bytes32,address)': TypedContractEvent<StrategyCancelledEvent.InputTuple, StrategyCancelledEvent.OutputTuple, StrategyCancelledEvent.OutputObject>;
      StrategyCancelled: TypedContractEvent<StrategyCancelledEvent.InputTuple, StrategyCancelledEvent.OutputTuple, StrategyCancelledEvent.OutputObject>;
    

      'StrategyCreated(bytes32,address,bytes32,uint64,uint64,uint8)': TypedContractEvent<StrategyCreatedEvent.InputTuple, StrategyCreatedEvent.OutputTuple, StrategyCreatedEvent.OutputObject>;
      StrategyCreated: TypedContractEvent<StrategyCreatedEvent.InputTuple, StrategyCreatedEvent.OutputTuple, StrategyCreatedEvent.OutputObject>;
    
    };
  }