/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace NoxveilEpochState {
      
    export type EpochPublicStruct = {openedAt: BigNumberish, lockedAt: BigNumberish, deadline: BigNumberish, participantCount: BigNumberish, epochNonce: BigNumberish, status: BigNumberish, twapPriceWad: BigNumberish, actionCommitment: BytesLike, residualDirectionHandle: BytesLike, residualAmountHandle: BytesLike, aggregateMinOutHandle: BytesLike, residualDirection: BigNumberish, residualAmount: BigNumberish, amountOutMinimum: BigNumberish, amountOut: BigNumberish}

    export type EpochPublicStructOutput = [openedAt: bigint, lockedAt: bigint, deadline: bigint, participantCount: bigint, epochNonce: bigint, status: bigint, twapPriceWad: bigint, actionCommitment: string, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string, residualDirection: bigint, residualAmount: bigint, amountOutMinimum: bigint, amountOut: bigint] & {openedAt: bigint, lockedAt: bigint, deadline: bigint, participantCount: bigint, epochNonce: bigint, status: bigint, twapPriceWad: bigint, actionCommitment: string, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string, residualDirection: bigint, residualAmount: bigint, amountOutMinimum: bigint, amountOut: bigint }
  
    }

  export interface NoxveilEpochStateInterface extends Interface {
    getFunction(nameOrSignature: "epochIdUsed" | "getEpoch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EpochCancelled" | "EpochLocked" | "EpochOpened" | "EpochReady" | "EpochSettled"): EventFragment;

    encodeFunctionData(functionFragment: 'epochIdUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getEpoch', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'epochIdUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEpoch', data: BytesLike): Result;
  }

  
    export namespace EpochCancelledEvent {
      export type InputTuple = [epochId: BytesLike];
      export type OutputTuple = [epochId: string];
      export interface OutputObject {epochId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochLockedEvent {
      export type InputTuple = [epochId: BytesLike, epochNonce: BigNumberish, twapPriceWad: BigNumberish, actionCommitment: BytesLike, residualDirectionHandle: BytesLike, residualAmountHandle: BytesLike, aggregateMinOutHandle: BytesLike];
      export type OutputTuple = [epochId: string, epochNonce: bigint, twapPriceWad: bigint, actionCommitment: string, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string];
      export interface OutputObject {epochId: string, epochNonce: bigint, twapPriceWad: bigint, actionCommitment: string, residualDirectionHandle: string, residualAmountHandle: string, aggregateMinOutHandle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochOpenedEvent {
      export type InputTuple = [epochId: BytesLike, epochNonce: BigNumberish, deadline: BigNumberish, participantCount: BigNumberish];
      export type OutputTuple = [epochId: string, epochNonce: bigint, deadline: bigint, participantCount: bigint];
      export interface OutputObject {epochId: string, epochNonce: bigint, deadline: bigint, participantCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochReadyEvent {
      export type InputTuple = [epochId: BytesLike, residualAmount: BigNumberish, amountOutMinimum: BigNumberish];
      export type OutputTuple = [epochId: string, residualAmount: bigint, amountOutMinimum: bigint];
      export interface OutputObject {epochId: string, residualAmount: bigint, amountOutMinimum: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochSettledEvent {
      export type InputTuple = [epochId: BytesLike, residualAmount: BigNumberish, amountOut: BigNumberish];
      export type OutputTuple = [epochId: string, residualAmount: bigint, amountOut: bigint];
      export interface OutputObject {epochId: string, residualAmount: bigint, amountOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxveilEpochState extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxveilEpochState;
    waitForDeployment(): Promise<this>;

    interface: NoxveilEpochStateInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    epochIdUsed: TypedContractMethod<
      [epochId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getEpoch: TypedContractMethod<
      [epochId: BytesLike, ],
      [NoxveilEpochState.EpochPublicStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'epochIdUsed'): TypedContractMethod<
      [epochId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getEpoch'): TypedContractMethod<
      [epochId: BytesLike, ],
      [NoxveilEpochState.EpochPublicStructOutput],
      'view'
    >;

    getEvent(key: 'EpochCancelled'): TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
getEvent(key: 'EpochLocked'): TypedContractEvent<EpochLockedEvent.InputTuple, EpochLockedEvent.OutputTuple, EpochLockedEvent.OutputObject>;
getEvent(key: 'EpochOpened'): TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
getEvent(key: 'EpochReady'): TypedContractEvent<EpochReadyEvent.InputTuple, EpochReadyEvent.OutputTuple, EpochReadyEvent.OutputObject>;
getEvent(key: 'EpochSettled'): TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;

    filters: {
      
      'EpochCancelled(bytes32)': TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
      EpochCancelled: TypedContractEvent<EpochCancelledEvent.InputTuple, EpochCancelledEvent.OutputTuple, EpochCancelledEvent.OutputObject>;
    

      'EpochLocked(bytes32,uint32,uint256,bytes32,bytes32,bytes32,bytes32)': TypedContractEvent<EpochLockedEvent.InputTuple, EpochLockedEvent.OutputTuple, EpochLockedEvent.OutputObject>;
      EpochLocked: TypedContractEvent<EpochLockedEvent.InputTuple, EpochLockedEvent.OutputTuple, EpochLockedEvent.OutputObject>;
    

      'EpochOpened(bytes32,uint32,uint64,uint32)': TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
      EpochOpened: TypedContractEvent<EpochOpenedEvent.InputTuple, EpochOpenedEvent.OutputTuple, EpochOpenedEvent.OutputObject>;
    

      'EpochReady(bytes32,uint256,uint256)': TypedContractEvent<EpochReadyEvent.InputTuple, EpochReadyEvent.OutputTuple, EpochReadyEvent.OutputObject>;
      EpochReady: TypedContractEvent<EpochReadyEvent.InputTuple, EpochReadyEvent.OutputTuple, EpochReadyEvent.OutputObject>;
    

      'EpochSettled(bytes32,uint256,uint256)': TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
      EpochSettled: TypedContractEvent<EpochSettledEvent.InputTuple, EpochSettledEvent.OutputTuple, EpochSettledEvent.OutputObject>;
    
    };
  }