/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface UniswapV3BatchSwapAdapterInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "controller" | "controllerLocked" | "poolFee" | "router" | "setController" | "swapExactInput" | "tokenIn" | "tokenOut"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'controller', values?: undefined): string;
encodeFunctionData(functionFragment: 'controllerLocked', values?: undefined): string;
encodeFunctionData(functionFragment: 'poolFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'router', values?: undefined): string;
encodeFunctionData(functionFragment: 'setController', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'swapExactInput', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenIn', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenOut', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'controller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'controllerLocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setController', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactInput', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenOut', data: BytesLike): Result;
  }

  

  export interface UniswapV3BatchSwapAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): UniswapV3BatchSwapAdapter;
    waitForDeployment(): Promise<this>;

    interface: UniswapV3BatchSwapAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    controller: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    controllerLocked: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    poolFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setController: TypedContractMethod<
      [newController: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    swapExactInput: TypedContractMethod<
      [suppliedTokenIn: AddressLike, suppliedTokenOut: AddressLike, amountIn: BigNumberish, minAmountOut: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    tokenIn: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenOut: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'controller'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'controllerLocked'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'poolFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setController'): TypedContractMethod<
      [newController: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapExactInput'): TypedContractMethod<
      [suppliedTokenIn: AddressLike, suppliedTokenOut: AddressLike, amountIn: BigNumberish, minAmountOut: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenIn'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenOut'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }