/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { NoxveilTickMath, NoxveilTickMathInterface } from "../../../v3/libraries/NoxveilTickMath.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "int24",
        "name": "tick",
        "type": "int24"
      }
    ],
    "name": "TickOutOfRange",
    "type": "error"
  }
] as const;

  const _bytecode = "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220f646ab7f1862199e8aba56e2365c875dee53dafe2d7869d2774c3af5653f864b64736f6c63430008230033";

  
      type NoxveilTickMathConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: NoxveilTickMathConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class NoxveilTickMath__factory extends ContractFactory {
    
      constructor(...args: NoxveilTickMathConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<NoxveilTickMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): NoxveilTickMath__factory {
      return super.connect(runner) as NoxveilTickMath__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): NoxveilTickMathInterface {
      return new Interface(_abi) as NoxveilTickMathInterface;
    }
    
    override attach(address: string | Addressable): NoxveilTickMath {
      return super.attach(address) as NoxveilTickMath;
    }
  static connect(address: string, runner?: ContractRunner | null): NoxveilTickMath {
      return new Contract(address, _abi, runner) as unknown as NoxveilTickMath;
    }
  }

  
  