/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { NoxveilMath, NoxveilMathInterface } from "../../../v3/libraries/NoxveilMath.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidAllocation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPrice",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSideInput",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint24",
        "name": "fee",
        "type": "uint24"
      }
    ],
    "name": "UnsupportedFee",
    "type": "error"
  }
] as const;

  const _bytecode = "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220b846bf7743c3c74bbe91ef95757d07d0adf9c0c5e0b827e7f59be1e69e1ade4764736f6c63430008230033";

  
      type NoxveilMathConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: NoxveilMathConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class NoxveilMath__factory extends ContractFactory {
    
      constructor(...args: NoxveilMathConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<NoxveilMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): NoxveilMath__factory {
      return super.connect(runner) as NoxveilMath__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): NoxveilMathInterface {
      return new Interface(_abi) as NoxveilMathInterface;
    }
    
    override attach(address: string | Addressable): NoxveilMath {
      return super.attach(address) as NoxveilMath;
    }
  static connect(address: string, runner?: ContractRunner | null): NoxveilMath {
      return new Contract(address, _abi, runner) as unknown as NoxveilMath;
    }
  }

  
  