/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { NoxveilEpochState, NoxveilEpochStateInterface } from "../../v3/NoxveilEpochState.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "supplied",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "expected",
        "type": "bytes32"
      }
    ],
    "name": "ActionCommitmentMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      }
    ],
    "name": "EpochAlreadyUsed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "deadline",
        "type": "uint64"
      }
    ],
    "name": "EpochDeadlineNotReached",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "deadline",
        "type": "uint64"
      }
    ],
    "name": "EpochDeadlinePassed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "deadline",
        "type": "uint64"
      }
    ],
    "name": "InvalidEpochDeadline",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidEpochId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidEpochLock",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      },
      {
        "internalType": "enum NoxveilEpochState.EpochStatus",
        "name": "actual",
        "type": "uint8"
      },
      {
        "internalType": "enum NoxveilEpochState.EpochStatus",
        "name": "expected",
        "type": "uint8"
      }
    ],
    "name": "InvalidEpochStatus",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "participantCount",
        "type": "uint32"
      }
    ],
    "name": "InvalidParticipantCount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amountOut",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "minimum",
        "type": "uint256"
      }
    ],
    "name": "InvalidSettlementOutput",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      }
    ],
    "name": "EpochCancelled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "epochNonce",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "twapPriceWad",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "actionCommitment",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "residualDirectionHandle",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "residualAmountHandle",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "aggregateMinOutHandle",
        "type": "bytes32"
      }
    ],
    "name": "EpochLocked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "epochNonce",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "deadline",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "participantCount",
        "type": "uint32"
      }
    ],
    "name": "EpochOpened",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "residualAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amountOutMinimum",
        "type": "uint256"
      }
    ],
    "name": "EpochReady",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "residualAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amountOut",
        "type": "uint256"
      }
    ],
    "name": "EpochSettled",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      }
    ],
    "name": "epochIdUsed",
    "outputs": [
      {
        "internalType": "bool",
        "name": "used",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "epochId",
        "type": "bytes32"
      }
    ],
    "name": "getEpoch",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint64",
            "name": "openedAt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "lockedAt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "deadline",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "participantCount",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "epochNonce",
            "type": "uint32"
          },
          {
            "internalType": "enum NoxveilEpochState.EpochStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "twapPriceWad",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "actionCommitment",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "residualDirectionHandle",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "residualAmountHandle",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "aggregateMinOutHandle",
            "type": "bytes32"
          },
          {
            "internalType": "uint8",
            "name": "residualDirection",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "residualAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "amountOutMinimum",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "amountOut",
            "type": "uint256"
          }
        ],
        "internalType": "struct NoxveilEpochState.EpochPublic",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class NoxveilEpochState__factory {
    static readonly abi = _abi;
    static createInterface(): NoxveilEpochStateInterface {
      return new Interface(_abi) as NoxveilEpochStateInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): NoxveilEpochState {
      return new Contract(address, _abi, runner) as unknown as NoxveilEpochState;
    }
  }
  