/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface NoxBatchEvaluatorInterface extends Interface {
    getFunction(nameOrSignature: "deliverNetting" | "nonce" | "requestNetting" | "requests" | "resultHandlesOf"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchNettingRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'deliverNetting', values: [BytesLike, [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike]]): string;
encodeFunctionData(functionFragment: 'nonce', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestNetting', values: [BytesLike, BigNumberish, [AddressLike, AddressLike, AddressLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BytesLike, BytesLike, BytesLike], [BigNumberish, BigNumberish, BigNumberish]]): string;
encodeFunctionData(functionFragment: 'requests', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'resultHandlesOf', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'deliverNetting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestNetting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resultHandlesOf', data: BytesLike): Result;
  }

  
    export namespace BatchNettingRequestedEvent {
      export type InputTuple = [epochId: BytesLike, requestId: BytesLike, firstDebitHandle: BytesLike];
      export type OutputTuple = [epochId: string, requestId: string, firstDebitHandle: string];
      export interface OutputObject {epochId: string, requestId: string, firstDebitHandle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoxBatchEvaluator extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoxBatchEvaluator;
    waitForDeployment(): Promise<this>;

    interface: NoxBatchEvaluatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deliverNetting: TypedContractMethod<
      [requestId: BytesLike, debitProofs: [BytesLike, BytesLike, BytesLike], outputProofs: [BytesLike, BytesLike, BytesLike], ],
      [void],
      'nonpayable'
    >
    

    
    nonce: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    requestNetting: TypedContractMethod<
      [epochId: BytesLike, epoch: BigNumberish, users: [AddressLike, AddressLike, AddressLike], amountHandles: [BytesLike, BytesLike, BytesLike], amountProofs: [BytesLike, BytesLike, BytesLike], minOutHandles: [BytesLike, BytesLike, BytesLike], minOutProofs: [BytesLike, BytesLike, BytesLike], escrowCaps: [BigNumberish, BigNumberish, BigNumberish], ],
      [string],
      'nonpayable'
    >
    

    
    requests: TypedContractMethod<
      [requestId: BytesLike, ],
      [[string, string, bigint] & {router: string, epochId: string, epoch: bigint }],
      'view'
    >
    

    
    resultHandlesOf: TypedContractMethod<
      [requestId: BytesLike, ],
      [[[string, string, string], [string, string, string]] & {debits: [string, string, string], outputs: [string, string, string] }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deliverNetting'): TypedContractMethod<
      [requestId: BytesLike, debitProofs: [BytesLike, BytesLike, BytesLike], outputProofs: [BytesLike, BytesLike, BytesLike], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nonce'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'requestNetting'): TypedContractMethod<
      [epochId: BytesLike, epoch: BigNumberish, users: [AddressLike, AddressLike, AddressLike], amountHandles: [BytesLike, BytesLike, BytesLike], amountProofs: [BytesLike, BytesLike, BytesLike], minOutHandles: [BytesLike, BytesLike, BytesLike], minOutProofs: [BytesLike, BytesLike, BytesLike], escrowCaps: [BigNumberish, BigNumberish, BigNumberish], ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requests'): TypedContractMethod<
      [requestId: BytesLike, ],
      [[string, string, bigint] & {router: string, epochId: string, epoch: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'resultHandlesOf'): TypedContractMethod<
      [requestId: BytesLike, ],
      [[[string, string, string], [string, string, string]] & {debits: [string, string, string], outputs: [string, string, string] }],
      'view'
    >;

    getEvent(key: 'BatchNettingRequested'): TypedContractEvent<BatchNettingRequestedEvent.InputTuple, BatchNettingRequestedEvent.OutputTuple, BatchNettingRequestedEvent.OutputObject>;

    filters: {
      
      'BatchNettingRequested(bytes32,bytes32,bytes32)': TypedContractEvent<BatchNettingRequestedEvent.InputTuple, BatchNettingRequestedEvent.OutputTuple, BatchNettingRequestedEvent.OutputObject>;
      BatchNettingRequested: TypedContractEvent<BatchNettingRequestedEvent.InputTuple, BatchNettingRequestedEvent.OutputTuple, BatchNettingRequestedEvent.OutputObject>;
    
    };
  }