/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NoxveilMath } from './NoxveilMath.js';
export type { NoxveilTickMath } from './NoxveilTickMath.js';