/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ISwapRouter02Minimal, ISwapRouter02MinimalInterface } from "../../../v3/interfaces/ISwapRouter02Minimal.js";

  const _abi = [
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "tokenIn",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "tokenOut",
            "type": "address"
          },
          {
            "internalType": "uint24",
            "name": "fee",
            "type": "uint24"
          },
          {
            "internalType": "address",
            "name": "recipient",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "amountIn",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "amountOutMinimum",
            "type": "uint256"
          },
          {
            "internalType": "uint160",
            "name": "sqrtPriceLimitX96",
            "type": "uint160"
          }
        ],
        "internalType": "struct ISwapRouter02Minimal.ExactInputSingleParams",
        "name": "params",
        "type": "tuple"
      }
    ],
    "name": "exactInputSingle",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "amountOut",
        "type": "uint256"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class ISwapRouter02Minimal__factory {
    static readonly abi = _abi;
    static createInterface(): ISwapRouter02MinimalInterface {
      return new Interface(_abi) as ISwapRouter02MinimalInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ISwapRouter02Minimal {
      return new Contract(address, _abi, runner) as unknown as ISwapRouter02Minimal;
    }
  }
  